### ISSUE TITLE
Panel height is not 100%

### ISSUE THREAD

**Issue by ghost** [alexandruionascu/youtube-pane#6]
Hi, just installed yotube-pane, it works but the panel height is not 100% and is not resizeable. Just tried to edit the config & less file, but i think i didn't edit correctly so doen't effect 

*I use atom with latest version

**Comment by alexandruionascu** [comment]
Thank you for your interest! If you have any pull-request suggestion please
feel free to contribute, thanks!

Pe vineri, 19 august 2016, bersujamu notifications@github.com a scris:

**Comment by simukka** [comment]
I'm also seeing this issue. After investigating the elements I was able to fix the view by adding `width:100%; height:100%` to the browser plugin object in the webview element.
